image: ubuntu1804

build: off

test_script:
- lsb_release -a
- pwsh --version
- docker version
- docker info
- git --version
- git lfs version
- hg --version
- svn --version
- dotnet --list-sdks
- dotnet --list-runtimes
- nvm --version
- nvm list
- gvm version
- gvm list
- mono --version
- if command -v sshd > /dev/null; then clang-9 --version; else echo "clang-9 is not installed"; fi
- if command -v sshd > /dev/null; then clang-10 --version; else echo "clang-10 is not installed"; fi
